version: '2'
services:
  db:
    image: postgres:9.4
    ports: 
      - 8432:5432
    environment:
      - POSTGRES_USER=waga
      - POSTGRES_PASSWORD=mysecretpassword 
      - POSTGRES_DB=waga
  mail:
    image: teggr/fakesmtp
    ports:
      - 8025:8025
